title: Fabio Franceschini
logo: /assets/img/logo-2_adj2.jpg
description: Macro-finance Researcher 
show_downloads: true
google_analytics: G-HKXH5THZR8
theme: jekyll-theme-minimal
url: "https://franceschini-f.github.io/" 
canonical_url: "https://franceschini-f.github.io/"
